[2025-10-04T12:07:01.218+0530] {processor.py:186} INFO - Started process (PID=9104) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:07:01.219+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py for tasks to queue
[2025-10-04T12:07:01.219+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:07:01.219+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:07:01.251+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:07:01.250+0530] {dagbag.py:387} ERROR - Failed to import: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py", line 7, in <module>
    from utils.airflow_tasks import run_data_pipeline, validate_input_data
ModuleNotFoundError: No module named 'utils'
[2025-10-04T12:07:01.252+0530] {processor.py:927} WARNING - No viable dags retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:07:01.942+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py took 0.727 seconds
[2025-10-04T12:09:39.540+0530] {processor.py:186} INFO - Started process (PID=41788) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:09:39.540+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py for tasks to queue
[2025-10-04T12:09:39.541+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:09:39.541+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:09:39.573+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:09:39.572+0530] {dagbag.py:387} ERROR - Failed to import: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py", line 7, in <module>
    from utils.airflow_tasks import run_data_pipeline, validate_input_data
ModuleNotFoundError: No module named 'utils'
[2025-10-04T12:09:39.573+0530] {processor.py:927} WARNING - No viable dags retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:09:40.279+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py took 0.743 seconds
[2025-10-04T12:15:14.698+0530] {processor.py:186} INFO - Started process (PID=25864) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:15:14.698+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py for tasks to queue
[2025-10-04T12:15:14.699+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:15:14.699+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:15:14.727+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:15:14.726+0530] {dagbag.py:387} ERROR - Failed to import: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py", line 7, in <module>
    from utils.airflow_tasks import run_data_pipeline, validate_input_data
ModuleNotFoundError: No module named 'utils'
[2025-10-04T12:15:14.727+0530] {processor.py:927} WARNING - No viable dags retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py
[2025-10-04T12:15:15.332+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\data_pipeline_dag.py took 0.637 seconds
