[2025-10-04T12:06:57.502+0530] {processor.py:186} INFO - Started process (PID=34428) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:06:57.502+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py for tasks to queue
[2025-10-04T12:06:57.503+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:06:57.503+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:06:57.538+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:06:57.537+0530] {dagbag.py:387} ERROR - Failed to import: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py", line 10, in <module>
    from utils.airflow_tasks import validate_processed_data, run_training_pipeline
ModuleNotFoundError: No module named 'utils'
[2025-10-04T12:06:57.538+0530] {processor.py:927} WARNING - No viable dags retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:06:58.215+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py took 0.716 seconds
[2025-10-04T12:09:35.846+0530] {processor.py:186} INFO - Started process (PID=24736) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:09:35.846+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py for tasks to queue
[2025-10-04T12:09:35.847+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:09:35.847+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:09:35.879+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:09:35.878+0530] {dagbag.py:387} ERROR - Failed to import: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py", line 10, in <module>
    from utils.airflow_tasks import validate_processed_data, run_training_pipeline
ModuleNotFoundError: No module named 'utils'
[2025-10-04T12:09:35.879+0530] {processor.py:927} WARNING - No viable dags retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:09:36.677+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py took 0.834 seconds
[2025-10-04T12:15:11.061+0530] {processor.py:186} INFO - Started process (PID=22632) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:15:11.061+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py for tasks to queue
[2025-10-04T12:15:11.062+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:15:11.061+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:15:11.092+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:15:11.091+0530] {dagbag.py:387} ERROR - Failed to import: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py", line 10, in <module>
    from utils.airflow_tasks import validate_processed_data, run_training_pipeline
ModuleNotFoundError: No module named 'utils'
[2025-10-04T12:15:11.092+0530] {processor.py:927} WARNING - No viable dags retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py
[2025-10-04T12:15:11.743+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.airflow\dags\train_pipeline_dag.py took 0.686 seconds
