[2025-10-04T12:07:21.034+0530] {processor.py:186} INFO - Started process (PID=35308) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:07:21.035+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py for tasks to queue
[2025-10-04T12:07:21.035+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:07:21.035+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:07:22.359+0530] {processor.py:925} INFO - DAG(s) 'tutorial_taskflow_templates' retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:07:22.553+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:07:22.544+0530] {dagbag.py:698} ERROR - Failed to write serialized DAG: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1663, in serialize_dag
    dag_deps = [
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1666, in <listcomp>
    for dep in SerializedBaseOperator.detect_dependencies(task)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1468, in detect_dependencies
    deps = set(dependency_detector.detect_task_dependencies(op))
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1026, in detect_task_dependencies
    from airflow.operators.trigger_dagrun import TriggerDagRunOperator
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\operators\trigger_dagrun.py", line 45, in <module>
    from airflow.triggers.external_task import DagStateTrigger
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\triggers\external_task.py", line 23, in <module>
    from asgiref.sync import sync_to_async
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\asgiref\sync.py", line 11, in <module>
    from concurrent.futures import Future, ThreadPoolExecutor
ImportError: cannot import name 'ThreadPoolExecutor' from 'concurrent.futures' (C:\Users\viraj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 686, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\utils\session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\serialized_dag.py", line 169, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\orm\state.py", line 481, in _initialize_instance
    with util.safe_reraise():
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\orm\state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\serialized_dag.py", line 116, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1776, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1685, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'tutorial_taskflow_templates': cannot import name 'ThreadPoolExecutor' from 'concurrent.futures' (C:\Users\viraj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\__init__.py)
[2025-10-04T12:07:22.554+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:07:22.554+0530] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-04T12:07:22.561+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:07:22.560+0530] {dag.py:3262} INFO - Creating ORM DAG for tutorial_taskflow_templates
[2025-10-04T12:07:22.566+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:07:22.566+0530] {dag.py:4180} INFO - Setting next_dagrun for tutorial_taskflow_templates to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T12:07:23.256+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py took 2.225 seconds
[2025-10-04T12:09:59.588+0530] {processor.py:186} INFO - Started process (PID=14076) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:09:59.588+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py for tasks to queue
[2025-10-04T12:09:59.589+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:09:59.589+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:10:00.853+0530] {processor.py:925} INFO - DAG(s) 'tutorial_taskflow_templates' retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:10:00.962+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:10:00.957+0530] {dagbag.py:698} ERROR - Failed to write serialized DAG: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1663, in serialize_dag
    dag_deps = [
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1666, in <listcomp>
    for dep in SerializedBaseOperator.detect_dependencies(task)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1468, in detect_dependencies
    deps = set(dependency_detector.detect_task_dependencies(op))
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1026, in detect_task_dependencies
    from airflow.operators.trigger_dagrun import TriggerDagRunOperator
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\operators\trigger_dagrun.py", line 45, in <module>
    from airflow.triggers.external_task import DagStateTrigger
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\triggers\external_task.py", line 23, in <module>
    from asgiref.sync import sync_to_async
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\asgiref\sync.py", line 11, in <module>
    from concurrent.futures import Future, ThreadPoolExecutor
ImportError: cannot import name 'ThreadPoolExecutor' from 'concurrent.futures' (C:\Users\viraj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 686, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\utils\session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\serialized_dag.py", line 169, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\orm\state.py", line 481, in _initialize_instance
    with util.safe_reraise():
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\orm\state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\serialized_dag.py", line 116, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1776, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1685, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'tutorial_taskflow_templates': cannot import name 'ThreadPoolExecutor' from 'concurrent.futures' (C:\Users\viraj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\__init__.py)
[2025-10-04T12:10:00.964+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:10:00.964+0530] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-04T12:10:00.981+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:10:00.981+0530] {dag.py:4180} INFO - Setting next_dagrun for tutorial_taskflow_templates to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T12:10:01.605+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py took 2.020 seconds
[2025-10-04T12:15:33.334+0530] {processor.py:186} INFO - Started process (PID=40288) to work on C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:15:33.335+0530] {processor.py:914} INFO - Processing file C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py for tasks to queue
[2025-10-04T12:15:33.336+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:15:33.335+0530] {dagbag.py:588} INFO - Filling up the DagBag from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:15:34.719+0530] {processor.py:925} INFO - DAG(s) 'tutorial_taskflow_templates' retrieved from C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
[2025-10-04T12:15:34.792+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:15:34.788+0530] {dagbag.py:698} ERROR - Failed to write serialized DAG: C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py
Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1663, in serialize_dag
    dag_deps = [
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1666, in <listcomp>
    for dep in SerializedBaseOperator.detect_dependencies(task)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1468, in detect_dependencies
    deps = set(dependency_detector.detect_task_dependencies(op))
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1026, in detect_task_dependencies
    from airflow.operators.trigger_dagrun import TriggerDagRunOperator
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\operators\trigger_dagrun.py", line 45, in <module>
    from airflow.triggers.external_task import DagStateTrigger
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\triggers\external_task.py", line 23, in <module>
    from asgiref.sync import sync_to_async
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\asgiref\sync.py", line 11, in <module>
    from concurrent.futures import Future, ThreadPoolExecutor
ImportError: cannot import name 'ThreadPoolExecutor' from 'concurrent.futures' (C:\Users\viraj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\dagbag.py", line 686, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\utils\session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\serialized_dag.py", line 169, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\orm\state.py", line 481, in _initialize_instance
    with util.safe_reraise():
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\sqlalchemy\orm\state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\models\serialized_dag.py", line 116, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1776, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\serialization\serialized_objects.py", line 1685, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'tutorial_taskflow_templates': cannot import name 'ThreadPoolExecutor' from 'concurrent.futures' (C:\Users\viraj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\__init__.py)
[2025-10-04T12:15:34.793+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:15:34.792+0530] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-04T12:15:34.804+0530] {logging_mixin.py:190} INFO - [2025-10-04T12:15:34.804+0530] {dag.py:4180} INFO - Setting next_dagrun for tutorial_taskflow_templates to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T12:15:35.427+0530] {processor.py:208} INFO - Processing C:\Users\viraj\Zuu\Customer_Churn_Prediction_Productionized\.venv\lib\site-packages\airflow\example_dags\tutorial_taskflow_templates.py took 2.096 seconds
